version: '2.2'

services:
    memcached:
        image: memcached:latest
        container_name: ${APP_NAME}_memcached
        ports:
            - "11212:11211"
#    redis:
#        container_name: ${APP_NAME}_redis
#        image: redis:alpine
#        ports:
#            - "6379:6379"
    php:
        container_name: ${APP_NAME}_php
        build:
            context: ./doc/docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
                APP_ENV: ${APP_ENV}
                APP_NAME: ${APP_NAME}
        volumes:
            - ${APP_PATH}:/var/www/sandbox:cached
            - ./var/log/sandbox:/var/www/sandbox/var/log
        links:
            - memcached
            #- redis
    nginx:
        container_name: ${APP_NAME}_nginx
        build:
            context: ./doc/docker/nginx
            args:
                MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
                SERVER_NAME: ${SERVER_NAME}
        ports:
            #- "8080:80"
            - "80:80"
        volumes_from:
            - php
        volumes:
            - ./var/log/nginx/:/var/log/nginx
    mysql:
        container_name: ${APP_NAME}_mysql
        image: mysql:5.7
        volumes:
            - "./doc/docker/.data/mysql:/var/lib/mysql"
            - "./doc/docker/mysql:/etc/mysql/conf.d"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3307:3306"
    rabbit:
        container_name: ${APP_NAME}_rabbit
        hostname: rabbit
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
        volumes:
            - ./doc/docker/.data/rabbitmq/:/var/lib/rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
    elk:
        container_name: ${APP_NAME}_elk
        image: sebp/elk
        volumes:
            - ./doc/docker/elk/logstash:/etc/logstash
            - ./doc/docker/elk/logstash/patterns:/opt/logstash/patterns
            - ./doc/docker/.data/elasticsearch:/var/lib/elasticsearch
            #- ./doc/docker/elk/elasticsearch:/etc/elasticsearch # to place elastisearch.yml configuration
        volumes_from:
            - php
            - nginx
        ports:
            - "5601:5601"
            - "9300:9200"
            - "5044:5044"